# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/franciscojaviernicolas/Work/HyperonsAna/PyCppTestProgram

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/franciscojaviernicolas/Work/HyperonsAna/PyCppTestProgram

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/franciscojaviernicolas/Work/HyperonsAna/PyCppTestProgram/CMakeFiles /Users/franciscojaviernicolas/Work/HyperonsAna/PyCppTestProgram//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/franciscojaviernicolas/Work/HyperonsAna/PyCppTestProgram/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pybind_wrapper

# Build rule for target.
pybind_wrapper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pybind_wrapper
.PHONY : pybind_wrapper

# fast build rule for target.
pybind_wrapper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pybind_wrapper.dir/build.make CMakeFiles/pybind_wrapper.dir/build
.PHONY : pybind_wrapper/fast

#=============================================================================
# Target rules for targets named mygeek

# Build rule for target.
mygeek: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mygeek
.PHONY : mygeek

# fast build rule for target.
mygeek/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/build
.PHONY : mygeek/fast

pybind_wrapper.o: pybind_wrapper.cpp.o

.PHONY : pybind_wrapper.o

# target to build an object file
pybind_wrapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pybind_wrapper.dir/build.make CMakeFiles/pybind_wrapper.dir/pybind_wrapper.cpp.o
.PHONY : pybind_wrapper.cpp.o

pybind_wrapper.i: pybind_wrapper.cpp.i

.PHONY : pybind_wrapper.i

# target to preprocess a source file
pybind_wrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pybind_wrapper.dir/build.make CMakeFiles/pybind_wrapper.dir/pybind_wrapper.cpp.i
.PHONY : pybind_wrapper.cpp.i

pybind_wrapper.s: pybind_wrapper.cpp.s

.PHONY : pybind_wrapper.s

# target to generate assembly for a file
pybind_wrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pybind_wrapper.dir/build.make CMakeFiles/pybind_wrapper.dir/pybind_wrapper.cpp.s
.PHONY : pybind_wrapper.cpp.s

src/TPCLinesAlgo.o: src/TPCLinesAlgo.cpp.o

.PHONY : src/TPCLinesAlgo.o

# target to build an object file
src/TPCLinesAlgo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCLinesAlgo.cpp.o
.PHONY : src/TPCLinesAlgo.cpp.o

src/TPCLinesAlgo.i: src/TPCLinesAlgo.cpp.i

.PHONY : src/TPCLinesAlgo.i

# target to preprocess a source file
src/TPCLinesAlgo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCLinesAlgo.cpp.i
.PHONY : src/TPCLinesAlgo.cpp.i

src/TPCLinesAlgo.s: src/TPCLinesAlgo.cpp.s

.PHONY : src/TPCLinesAlgo.s

# target to generate assembly for a file
src/TPCLinesAlgo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCLinesAlgo.cpp.s
.PHONY : src/TPCLinesAlgo.cpp.s

src/TPCLinesDisplay.o: src/TPCLinesDisplay.cpp.o

.PHONY : src/TPCLinesDisplay.o

# target to build an object file
src/TPCLinesDisplay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCLinesDisplay.cpp.o
.PHONY : src/TPCLinesDisplay.cpp.o

src/TPCLinesDisplay.i: src/TPCLinesDisplay.cpp.i

.PHONY : src/TPCLinesDisplay.i

# target to preprocess a source file
src/TPCLinesDisplay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCLinesDisplay.cpp.i
.PHONY : src/TPCLinesDisplay.cpp.i

src/TPCLinesDisplay.s: src/TPCLinesDisplay.cpp.s

.PHONY : src/TPCLinesDisplay.s

# target to generate assembly for a file
src/TPCLinesDisplay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCLinesDisplay.cpp.s
.PHONY : src/TPCLinesDisplay.cpp.s

src/TPCLinesHough.o: src/TPCLinesHough.cpp.o

.PHONY : src/TPCLinesHough.o

# target to build an object file
src/TPCLinesHough.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCLinesHough.cpp.o
.PHONY : src/TPCLinesHough.cpp.o

src/TPCLinesHough.i: src/TPCLinesHough.cpp.i

.PHONY : src/TPCLinesHough.i

# target to preprocess a source file
src/TPCLinesHough.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCLinesHough.cpp.i
.PHONY : src/TPCLinesHough.cpp.i

src/TPCLinesHough.s: src/TPCLinesHough.cpp.s

.PHONY : src/TPCLinesHough.s

# target to generate assembly for a file
src/TPCLinesHough.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCLinesHough.cpp.s
.PHONY : src/TPCLinesHough.cpp.s

src/TPCLinesParameters.o: src/TPCLinesParameters.cpp.o

.PHONY : src/TPCLinesParameters.o

# target to build an object file
src/TPCLinesParameters.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCLinesParameters.cpp.o
.PHONY : src/TPCLinesParameters.cpp.o

src/TPCLinesParameters.i: src/TPCLinesParameters.cpp.i

.PHONY : src/TPCLinesParameters.i

# target to preprocess a source file
src/TPCLinesParameters.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCLinesParameters.cpp.i
.PHONY : src/TPCLinesParameters.cpp.i

src/TPCLinesParameters.s: src/TPCLinesParameters.cpp.s

.PHONY : src/TPCLinesParameters.s

# target to generate assembly for a file
src/TPCLinesParameters.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCLinesParameters.cpp.s
.PHONY : src/TPCLinesParameters.cpp.s

src/TPCLinesTrackFinder.o: src/TPCLinesTrackFinder.cpp.o

.PHONY : src/TPCLinesTrackFinder.o

# target to build an object file
src/TPCLinesTrackFinder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCLinesTrackFinder.cpp.o
.PHONY : src/TPCLinesTrackFinder.cpp.o

src/TPCLinesTrackFinder.i: src/TPCLinesTrackFinder.cpp.i

.PHONY : src/TPCLinesTrackFinder.i

# target to preprocess a source file
src/TPCLinesTrackFinder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCLinesTrackFinder.cpp.i
.PHONY : src/TPCLinesTrackFinder.cpp.i

src/TPCLinesTrackFinder.s: src/TPCLinesTrackFinder.cpp.s

.PHONY : src/TPCLinesTrackFinder.s

# target to generate assembly for a file
src/TPCLinesTrackFinder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCLinesTrackFinder.cpp.s
.PHONY : src/TPCLinesTrackFinder.cpp.s

src/TPCSimpleClusters.o: src/TPCSimpleClusters.cpp.o

.PHONY : src/TPCSimpleClusters.o

# target to build an object file
src/TPCSimpleClusters.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCSimpleClusters.cpp.o
.PHONY : src/TPCSimpleClusters.cpp.o

src/TPCSimpleClusters.i: src/TPCSimpleClusters.cpp.i

.PHONY : src/TPCSimpleClusters.i

# target to preprocess a source file
src/TPCSimpleClusters.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCSimpleClusters.cpp.i
.PHONY : src/TPCSimpleClusters.cpp.i

src/TPCSimpleClusters.s: src/TPCSimpleClusters.cpp.s

.PHONY : src/TPCSimpleClusters.s

# target to generate assembly for a file
src/TPCSimpleClusters.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCSimpleClusters.cpp.s
.PHONY : src/TPCSimpleClusters.cpp.s

src/TPCSimpleHits.o: src/TPCSimpleHits.cpp.o

.PHONY : src/TPCSimpleHits.o

# target to build an object file
src/TPCSimpleHits.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCSimpleHits.cpp.o
.PHONY : src/TPCSimpleHits.cpp.o

src/TPCSimpleHits.i: src/TPCSimpleHits.cpp.i

.PHONY : src/TPCSimpleHits.i

# target to preprocess a source file
src/TPCSimpleHits.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCSimpleHits.cpp.i
.PHONY : src/TPCSimpleHits.cpp.i

src/TPCSimpleHits.s: src/TPCSimpleHits.cpp.s

.PHONY : src/TPCSimpleHits.s

# target to generate assembly for a file
src/TPCSimpleHits.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCSimpleHits.cpp.s
.PHONY : src/TPCSimpleHits.cpp.s

src/TPCSimpleLines.o: src/TPCSimpleLines.cpp.o

.PHONY : src/TPCSimpleLines.o

# target to build an object file
src/TPCSimpleLines.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCSimpleLines.cpp.o
.PHONY : src/TPCSimpleLines.cpp.o

src/TPCSimpleLines.i: src/TPCSimpleLines.cpp.i

.PHONY : src/TPCSimpleLines.i

# target to preprocess a source file
src/TPCSimpleLines.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCSimpleLines.cpp.i
.PHONY : src/TPCSimpleLines.cpp.i

src/TPCSimpleLines.s: src/TPCSimpleLines.cpp.s

.PHONY : src/TPCSimpleLines.s

# target to generate assembly for a file
src/TPCSimpleLines.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/TPCSimpleLines.cpp.s
.PHONY : src/TPCSimpleLines.cpp.s

src/mygeek.o: src/mygeek.cpp.o

.PHONY : src/mygeek.o

# target to build an object file
src/mygeek.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/mygeek.cpp.o
.PHONY : src/mygeek.cpp.o

src/mygeek.i: src/mygeek.cpp.i

.PHONY : src/mygeek.i

# target to preprocess a source file
src/mygeek.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/mygeek.cpp.i
.PHONY : src/mygeek.cpp.i

src/mygeek.s: src/mygeek.cpp.s

.PHONY : src/mygeek.s

# target to generate assembly for a file
src/mygeek.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mygeek.dir/build.make CMakeFiles/mygeek.dir/src/mygeek.cpp.s
.PHONY : src/mygeek.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mygeek"
	@echo "... pybind_wrapper"
	@echo "... pybind_wrapper.o"
	@echo "... pybind_wrapper.i"
	@echo "... pybind_wrapper.s"
	@echo "... src/TPCLinesAlgo.o"
	@echo "... src/TPCLinesAlgo.i"
	@echo "... src/TPCLinesAlgo.s"
	@echo "... src/TPCLinesDisplay.o"
	@echo "... src/TPCLinesDisplay.i"
	@echo "... src/TPCLinesDisplay.s"
	@echo "... src/TPCLinesHough.o"
	@echo "... src/TPCLinesHough.i"
	@echo "... src/TPCLinesHough.s"
	@echo "... src/TPCLinesParameters.o"
	@echo "... src/TPCLinesParameters.i"
	@echo "... src/TPCLinesParameters.s"
	@echo "... src/TPCLinesTrackFinder.o"
	@echo "... src/TPCLinesTrackFinder.i"
	@echo "... src/TPCLinesTrackFinder.s"
	@echo "... src/TPCSimpleClusters.o"
	@echo "... src/TPCSimpleClusters.i"
	@echo "... src/TPCSimpleClusters.s"
	@echo "... src/TPCSimpleHits.o"
	@echo "... src/TPCSimpleHits.i"
	@echo "... src/TPCSimpleHits.s"
	@echo "... src/TPCSimpleLines.o"
	@echo "... src/TPCSimpleLines.i"
	@echo "... src/TPCSimpleLines.s"
	@echo "... src/mygeek.o"
	@echo "... src/mygeek.i"
	@echo "... src/mygeek.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

